### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by jtyang** [LaiFeng-Android/SopCastComponent#1]
我的nexus 6p前置摄像头是倒的--旋转了180度；有时候还特别暗；
另外请问下美颜这块能否接入GPUImage呢？

**Comment by SuperJim123** [comment]
比较穷没这款手机。然后，特别暗应该是前置摄像头不支持fps24帧吧，之后这边有这款手机了再试试。关于GPUImage我之前看过，主要是GPUImage处理后的效果很差，所以没有加，里面有Effect接口，熟悉OpenGL可以自己实现。

**Comment by SuperJim123** [comment]
@jtyang 已经修复，你更新下代码就好了。
