### ISSUE TITLE
截屏问题

### ISSUE THREAD

**Issue by nullptrx** [LaiFeng-Android/SopCastComponent#11]
调用录屏功能时，退出到后台，保持屏幕当前状态不操作，一会儿后得不到屏幕捕捉到的数据，观看端会呈现花屏的情况，请问这个如何处理？ @SuperJim123

**Comment by SuperJim123** [comment]
@liujunhongz 这个是因为长期画面没有改变，编码器编码后没有关键帧，这样导致观看端没有关键帧从而出现花屏，暂时没有想到解决办法，这个直播组件对录屏功能支持不是很好，只是提供了一个解决方式。
