### ISSUE TITLE
想请问下关于视频采集

### ISSUE THREAD

**Issue by ab503044120** [LaiFeng-Android/SopCastComponent#12]
我看网上很多博客都是通过setPreviewCallbackWithBuffer来采集视频数据,然后用MediaCodec来编码,我看你这边不是这样做的,是采用什么方法呢(新手看不懂,见谅)

**Comment by SuperJim123** [comment]
@ab503044120 这个是因为camera预览可以设置Preview texture，从而和OpenGL建立联系，将camera预览的数据以纹理的方式返回，之后通过纹理进行绘制，从而得到摄像头预览的界面。

**Comment by ab503044120** [comment]
@SuperJim123 那用来编码的的数据来源呢
