### ISSUE TITLE
能录制视频保存到本地吗

### ISSUE THREAD

**Issue by af913337456** [LaiFeng-Android/SopCastComponent#13]

**Comment by af913337456** [comment]
希望大神不介意的话，加下我Q，还有一些录制尺寸的问题想请教下，谢谢了！！

**Comment by SuperJim123** [comment]
@af913337456 可以存本地，但是是flv格式的，下个版本增加mp4格式的。录制尺寸通过VideoConfiguration设置。

**Comment by af913337456** [comment]
貌似在 API 里面没看到，save 之类的函数
