### ISSUE TITLE
如何直播图片+音频

### ISSUE THREAD

**Issue by GraphicSound** [LaiFeng-Android/SopCastComponent#14]
因为自带的截屏功能会截取整个屏幕，我们只想截取屏幕当中部分控件，所以我们不断地去截图这个控件，之后再和音频混编，推流，怎么做，望大神指导~

**Comment by SuperJim123** [comment]
@GraphicSound VirtualDisplay可以设置Surface，然而Surface可以通过SurfaceTexture生成，那么VirtualDisplay得到的图像可以转化为纹理，然后对纹理进行裁剪变形处理，之后通过OpenGL将数据塞到硬编编码器生成h264，再对h264和编码后的音频进行包装，包装成rtmp，之后推送就好了。另外多说一句，我们截屏直播写的不是那么完善，最好不要用activity方式的实现，最好写成service。祝你好运！

**Comment by GraphicSound** [comment]
@SuperJim123 非常感谢，不过感觉很难呀！！！

**Comment by SuperJim123** [comment]
@GraphicSound 主要是你没怎么写过，也不是很懂OpenGL，写过的话然后也懂OpenGL会简单很多。
