### ISSUE TITLE
屏幕不动的时候不传的问题

### ISSUE THREAD

**Issue by SunShaoNing** [LaiFeng-Android/SopCastComponent#16]
屏幕没有变化 的时候，没有数据传送时，就会有延迟，如果在刚开始传屏的时候就会传不上去数据，然后非得等屏幕变化之后才会传数据，那这之间的等待时间感觉就变成延迟了！

**Comment by SuperJim123** [comment]
@SunShaoNing 截屏直播只是demo级别的  主要是给个思路  不建议直接使用
