### ISSUE TITLE
替换视频特效glsl文件时，GlUtil.checkGlError("draw_E")，这段代码报异常

### ISSUE THREAD

**Issue by jiandang** [LaiFeng-Android/SopCastComponent#19]
替换视频特效glsl文件时，GlUtil.checkGlError("draw_E")，这段代码报异常

**Comment by SuperJim123** [comment]
@jiandang 应该是glsl文件写错了吧～  一些变量有没有写错？要对应上才可以

**Comment by jiandang** [comment]
但是同样的glsl文件，来疯app上面就可以运行，无语

**Comment by zhaocheng19940105** [comment]
请问有没有现成的美颜glsl

**Comment by SuperJim123** [comment]
@zhaocheng19940105 美颜的自己网上找找吧
