### ISSUE TITLE
你好 ，我需要一个美颜功能，请求我应该怎么做呢

### ISSUE THREAD

**Issue by JsonNC** [LaiFeng-Android/SopCastComponent#2]

**Comment by SuperJim123** [comment]
@JsonNC 美颜功能本来属于我司比较核心的技术，暂时没有公开，过些时候我根据GPUImageView搞一个简单版本的。其实了解OpenGL的话，可以看看GPUImageView的代码，然后抄一段过来就好了。

**Comment by SuperJim123** [comment]
@JsonNC mLFLiveView.setEffect(mGrayEffect);这个是加灰白的特效，可以参考下。

**Comment by JsonNC** [comment]
@SuperJim123 好的    已经弄出来了  感谢你的回复

**Comment by JsonNC** [comment]
@发热问题怎么处理处理呢  挺热的

**Comment by SuperJim123** [comment]
@JsonNC 一般来说直播加美颜是会发热（其他直播产品也存在这样的问题），美颜算法不好就会发热严重。当然我们代码也有需要优化的地方，欢迎提出宝贵意见。

**Comment by JsonNC** [comment]
@SuperJim123 大神 加个QQ吧  这是我的80464032
