### ISSUE TITLE
前鏡頭鏡像轉換

### ISSUE THREAD

**Issue by WilliamLuoKnife** [LaiFeng-Android/SopCastComponent#24]
請問有方法可以讓前鏡頭不做鏡像嗎，ios的sdk有可以設置Mirror參數使前鏡頭不做鏡像，想問android版的sdk有辦法嗎

**Comment by SuperJim123** [comment]
我记得也有，你自己找下

**Comment by SuperJim123** [comment]
@WilliamLuoKnife 好像没加  过段时间我加下吧

**Comment by WilliamLuoKnife** [comment]
感謝~如果好了通知一下，感謝@@

**Comment by RunningSnailGOAhead** [comment]
@SuperJim123 你好，请问不做镜像的思路是什么？能提示下嘛？
