### ISSUE TITLE
推流格式

### ISSUE THREAD

**Issue by xulingchung2016** [LaiFeng-Android/SopCastComponent#36]
问一下楼主，目前推流格式是什么？h.264吗？还是.flv

**Comment by SuperJim123** [comment]
flv的

**Comment by xulingchung2016** [comment]
哦，推流之前不用鞋flvheader 和元数据也可以？我看推流的只写了videoTag和audioTag，本地保存的还写了flvHeader和metadata.

**Comment by SuperJim123** [comment]
都写了flvheader和元数据
