### ISSUE TITLE
直播声音断断续续的

### ISSUE THREAD

**Issue by nullptrx** [LaiFeng-Android/SopCastComponent#43]
如题，请问怎么调试 @SuperJim123

**Comment by moliyadi** [comment]
声音卡顿的问题我们也碰到了，尤其是Server端转为TS或HLS推流后再使用vlc播放感知更加明显。分析了下代码，可能是RTMP chunk header中的timestamp问题，当前代码中使用的是网络发送数据的时间戳，尝试修改为摄像头采集数据的编码时间戳后就没有声音卡顿问题了，供其他人参考吧；

具体修改可以参考下这次提交：
https://github.com/moliyadi/SopCastComponent/commit/91c295b697d7af5ba75123c6371845cc9eb8950b
