### ISSUE TITLE
How to connect two devices

### ISSUE THREAD

**Issue by HuuNguyen312** [LaiFeng-Android/SopCastComponent#5]
Hi,

I want to test your library. But I do not see the link RTMP. Hơ to connect two devices

**Comment by SuperJim123** [comment]
@ngochuu90 This is a component for RTMP uploading client. if you want to test this library: 
1. You must have a RTMP server, you can get a free RTMP server by Googling(rtmp://live.hkstv.hk.lxdns.com:1935/live/[your stream name] is a good one).
2. Use this component and set the right uploading url(such as rtmp://live.hkstv.hk.lxdns.com:1935/live/[your stream name]).
3. Find a RTMP player(VLC is a good one) to play this network video.

**Comment by HuuNguyen312** [comment]
Thanks. Your answer is great.
