### ISSUE TITLE
fail to publish the stream

### ISSUE THREAD

**Issue by SunShaoNing** [LaiFeng-Android/SopCastComponent#9]
不能录屏推流，设置了url不行，提示这个fail to publish the stream，希望能公开一个rtmp地址格式！

**Comment by SuperJim123** [comment]
@SunShaoNing You must have a RTMP server, you can get a free RTMP server by Googling(rtmp://live.hkstv.hk.lxdns.com:1935/live/[your stream name] is a good one).
